#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

#-----------
# Configurations
#-----------

export LAUNCHER_DIR=${LAUNCHER_DIR-/var/local}
export MYSQL_LAUNCHER_DIR=${MYSQL_LAUNCHER_DIR-$LAUNCHER_DIR/mysql}
export DATA_DIR=${DATA_DIR-/var/local/data}
export MYSQL_DATA_DIR=${MYSQL_DATA_DIR-${DATA_DIR}/mysql}
export MYSQL_PORT=${MYSQL_PORT-3306}
LAUNCHER_OWNER=${LAUNCHER_OWNER-$USER}
MYSQL_ADMIN_USERNAME=${MYSQL_ADMIN_USERNAME-admin}
MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD-yth3fn0t}

#-----------
# Install Script
#-----------

notify "Install mysql..."

if [[ "`which mysql 2> /dev/null`" == "" ]]; then
  apt-get install -y mysql-client
fi

OWNER=$LAUNCHER_OWNER ./bits/bootstrap/mkdir MYSQL_LAUNCHER_DIR MYSQL_DATA_DIR ${MYSQL_LAUNCHER_DIR}/bin
TEMPLATE=./bits/mysql/files/mysql.dockerfile LOCATION=${MYSQL_LAUNCHER_DIR}/Dockerfile ./bits/docker/copyif
TEMPLATE=./bits/mysql/files/bin LOCATION=${MYSQL_LAUNCHER_DIR}/bin ./bits/docker/copyallif
TEMPLATE=./bits/bootstrap/logging LOCATION=${MYSQL_LAUNCHER_DIR}/bin/logging ./bits/docker/copyif

OWNER=$LAUNCHER_OWNER LAUNCHER_DIR=$MYSQL_LAUNCHER_DIR NAME=mysql VERSION=latest ./bits/docker/build

printf "%b" "#!/bin/bash
docker run \\
  -e MYSQL_ADMIN_USERNAME=$MYSQL_ADMIN_USERNAME \\
  -e MYSQL_ADMIN_PASSWORD=$MYSQL_ADMIN_PASSWORD \\
  -p $MYSQL_PORT:3306 \\
  -v $MYSQL_DATA_DIR:/data \\
  mysql setup_mysql
" > ${MYSQL_LAUNCHER_DIR}/init

printf "%b" "#!/bin/bash
IP=\$(${MYSQL_LAUNCHER_DIR}/ip)
if [[ \"\$IP\" == '' ]]; then
  echo 'MYSQL not running (no IP available), cannot connect.'
else
  echo \"Connecting to mysql.local (\$IP) as $MYSQL_ADMIN_USERNAME\"
  mysql -u $MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h mysql.local
fi
" > ${MYSQL_LAUNCHER_DIR}/connect

printf "%b" "#!/bin/bash
docker exec -it \\
  -e MYSQL_ADMIN_USERNAME=$MYSQL_ADMIN_USERNAME \\
  -e MYSQL_ADMIN_PASSWORD=$MYSQL_ADMIN_PASSWORD \\
  -e DATABASE=$DATABASE \\
  -e USERNAME=$USERNAME \\
  -e PASSWORD=$PASSWORD \\
  -p $MYSQL_PORT:3306 \\
  -v $MYSQL_DATA_DIR:/data \\
  mysql newdb
" > ${MYSQL_LAUNCHER_DIR}/newdb

NAME=mysql DIR=$MYSQL_LAUNCHER_DIR \
  START=./bits/mysql/files/_start \
  DEBUG=./bits/mysql/files/_debug \
  ./bits/docker/helpers

chmod 755 $MYSQL_LAUNCHER_DIR/init
chmod 755 $MYSQL_LAUNCHER_DIR/connect
chmod 755 $MYSQL_LAUNCHER_DIR/newdb

$MYSQL_LAUNCHER_DIR/init

notify "DONE, Install mysql."
