#!/bin/bash

if [[ ! -e "/data/mysql" ]]; then
  echo "Initalizing MYSQL data"
  mysql_install_db --user=mysql --datadir=/data

  TEMP_FILE='/tmp/mysql-first-time.sql'
  echo "" > "$TEMP_FILE"
  echo "DELETE FROM mysql.user ;" >> "$TEMP_FILE"
  echo "CREATE USER '${MYSQL_ADMIN_USER}'@'%' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}' ;" >> "$TEMP_FILE"
  echo "GRANT ALL ON *.* TO '${MYSQL_ADMIN_USER}'@'%' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}' WITH GRANT OPTION ;" >> "$TEMP_FILE"
  echo "DROP DATABASE IF EXISTS test ;" >> "$TEMP_FILE"
  echo 'FLUSH PRIVILEGES ;' >> "$TEMP_FILE"

  /usr/bin/mysqld_safe --user=mysql --datadir=/data &
  sleep 10s
  cat "$TEMP_FILE" | mysql

  killall mysqld
  sleep 10s
else
  echo "MYSQL data already intialized"
fi
chown -R mysql:mysql /data
